fun main(){
    println("Enter number: ")
    var sEnrollmentNumber=readLine()!!.toInt()
    println(" Student Enrollment No. : $sEnrollmentNumber")
    println("Enter Name:")
    val name = readLine()
    println("Student name: $name")
    println("Enter Branch:")
    val branch = readLine()
    println("Student Branch:$branch")
    println("Enter  class name:")
    val classname = readLine()
    println("Student class:$classname")
    println("Enter  batch name:")
    val batchname = readLine()
    println("Student Batch:$batchname")
    println("Enter collage name:")
    val collagename = readLine()
    println("Student collage name:$collagename")
    println("Enter university name:")
    val universityname = readLine()
    println("Student university name:$universityname")
    println("Enter age:")
    var age = readLine()!!.toInt()
    println("Student age:$age")
}